name: mukandozw
description: MukandoZW Offline Bindura
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
flutter:
  uses-material-design: true
